"""empty message

Revision ID: 9f8cf9d8f2ba
Revises: ade048efa130
Create Date: 2024-09-09 01:05:33.204404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8cf9d8f2ba'
down_revision = 'ade048efa130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=80), nullable=False),
    sa.Column('initial_state', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.Date(), nullable=True),
    sa.Column('credit_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('register_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('url_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('url_image')
        batch_op.drop_column('register_date')
        batch_op.drop_column('name')

    op.drop_table('account')
    # ### end Alembic commands ###
